<a href="https://colab.research.google.com/github/yusibovmuraz/DataScience-1/blob/main/Homework5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Case Intro
Term deposits are a major source of income for a bank. A term deposit is a cash investment held at a financial institution. Your money is invested for an agreed rate of interest over a fixed amount of time, or term. The bank has various outreach plans to sell term deposits to their customers such as email marketing, advertisements, telephonic marketing, and digital marketing.

Telephonic marketing campaigns still remain one of the most effective way to reach out to people. However, they require huge investment as large call centers are hired to actually execute these campaigns. Hence, it is crucial to identify the customers most likely to convert beforehand so that they can be specifically targeted via call.

The data is related to direct marketing campaigns (phone calls) of a Portuguese banking institution. The classification goal is to predict if the client will subscribe to a term deposit (variable y).

Content
The data is related to the direct marketing campaigns of a Portuguese banking institution. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed by the customer or not. The data folder contains two datasets:-

Bank.csv: 45,211 rows and 18 columns ordered by date (from May 2008 to November 2010)

Detailed Column Descriptions
bank client data:

1 - age (numeric)

2 - job : type of job (categorical: "admin.","unknown","unemployed","management","housemaid","entrepreneur","student",
"blue-collar","self-employed","retired","technician","services")

3 - marital : marital status (categorical: "married","divorced","single"; note: "divorced" means divorced or widowed)

4 - education (categorical: "unknown","secondary","primary","tertiary")

5 - default: has credit in default? (binary: "yes","no")

6 - balance: average yearly balance, in euros (numeric)

7 - housing: has housing loan? (binary: "yes","no")

8 - loan: has personal loan? (binary: "yes","no")
# related with the last contact of the current campaign:
9 - contact: contact communication type (categorical: "unknown","telephone","cellular")
10 - day: last contact day of the month (numeric)

11 - month: last contact month of year (categorical: "jan", "feb", "mar", â€¦, "nov", "dec")

12 - duration: last contact duration, in seconds (numeric)

# other attributes:
13 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)

14 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric, -1 means client was not previously contacted)

15 - previous: number of contacts performed before this campaign and for this client (numeric)

16 - poutcome: outcome of the previous marketing campaign (categorical: "unknown","other","failure","success")

Output variable (desired target):

17 - y - has the client subscribed a term deposit? (binary: "yes","no")

Missing Attribute Values: None

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('https://raw.githubusercontent.com/ogut77/DataScience/main/data/Bank.csv',sep = ';')
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [2]:
print(df.shape)
df.info()
df.isnull().sum()

(45211, 17)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [3]:
#For object check the data 
for cn in df.columns:
  if(df[cn].dtype==object):
    print(df[cn].value_counts())

blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: job, dtype: int64
married     27214
single      12790
divorced     5207
Name: marital, dtype: int64
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: education, dtype: int64
no     44396
yes      815
Name: default, dtype: int64
yes    25130
no     20081
Name: housing, dtype: int64
no     37967
yes     7244
Name: loan, dtype: int64
cellular     29285
unknown      13020
telephone     2906
Name: contact, dtype: int64
may    13766
jul     6895
aug     6247
jun     5341
nov     3970
apr     2932
feb     2649
jan     1403
oct      738
sep      579
mar      477
dec      214
Name: month, dtype: int64
unknown    36959
failure     4901
other       1840
success     1511
Name: poutcome, dtype: int64
no     39922
yes     5289
Name: y, dtype: int64

In [4]:
def Encoder(df):
          from sklearn import preprocessing
          columnsToEncode = list(df.select_dtypes(include=['category','object']))
          le = preprocessing.LabelEncoder()
          for feature in columnsToEncode:
              try:
                  df[feature] = le.fit_transform(df[feature])
              except:
                  print('Error encoding '+feature)
          return df

In [5]:
df=Encoder(df)
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,4,1,2,0,2143,1,0,2,5,8,261,1,-1,0,3,0
1,44,9,2,1,0,29,1,0,2,5,8,151,1,-1,0,3,0
2,33,2,1,1,0,2,1,1,2,5,8,76,1,-1,0,3,0
3,47,1,1,3,0,1506,1,0,2,5,8,92,1,-1,0,3,0
4,33,11,2,3,0,1,0,0,2,5,8,198,1,-1,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,9,1,2,0,825,0,0,0,17,9,977,3,-1,0,3,1
45207,71,5,0,0,0,1729,0,0,0,17,9,456,2,-1,0,3,1
45208,72,5,1,1,0,5715,0,0,0,17,9,1127,5,184,3,2,1
45209,57,1,1,1,0,668,0,0,1,17,9,508,4,-1,0,3,0
45210,37,2,1,1,0,2971,0,0,0,17,9,361,2,188,11,1,0

In [6]:
y = df['y'] #Output
X = df.drop('y',axis=1)
X

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome
0,58,4,1,2,0,2143,1,0,2,5,8,261,1,-1,0,3
1,44,9,2,1,0,29,1,0,2,5,8,151,1,-1,0,3
2,33,2,1,1,0,2,1,1,2,5,8,76,1,-1,0,3
3,47,1,1,3,0,1506,1,0,2,5,8,92,1,-1,0,3
4,33,11,2,3,0,1,0,0,2,5,8,198,1,-1,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,9,1,2,0,825,0,0,0,17,9,977,3,-1,0,3
45207,71,5,0,0,0,1729,0,0,0,17,9,456,2,-1,0,3
45208,72,5,1,1,0,5715,0,0,0,17,9,1127,5,184,3,2
45209,57,1,1,1,0,668,0,0,1,17,9,508,4,-1,0,3
45210,37,2,1,1,0,2971,0,0,0,17,9,361,2,188,11,1

In [7]:
from sklearn.model_selection import  train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=17)

 


Q1)Using  Random Forest,XGBoost, Light GBM and Gradient Boosting Classifier with default parameters (no parameter specifications except random_state) calculate Accuracy on Test data. Which method gives the best accuracy on test data

In [8]:
# Random Forest:
from sklearn.metrics import accuracy_score

from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(random_state=15)
forest.fit(X_train, y_train)

forest_pred = forest.predict(X_test)
print(accuracy_score(y_test, forest_pred))

# XGBoost:
from xgboost import XGBClassifier
model = XGBClassifier(random_state=15)
model.fit(X_train, y_train)

xgb_pred = model.predict(X_test)
print(accuracy_score(y_test, xgb_pred))

# Light GBM:
import lightgbm as lgb
lgb_model = lgb.LGBMClassifier(random_state=15)
lgb_model.fit(X_train, y_train)

print(accuracy_score(y_test, lgb_model.predict(X_test)))

# Gradient Boosting Classifier:
from sklearn.ensemble import GradientBoostingClassifier
gbm_model = GradientBoostingClassifier(random_state=15)
gbm_model.fit(X_train, y_train)

print(accuracy_score(y_test, gbm_model.predict(X_test)))

0.904007785543661
0.90020348580023
0.9044501459789437
0.9018844554543042

Q2) Using optuna hyperparmeter optimization technique and 100 trial

 a)find best methods with  parameters  using Cross validation (CV=3) technique for the range of   parameters below. What are the best parameters for the method with highest cross validation accuracy?

"max_depth": range(2, 16), "max_features": range(2, 16)

 b)Evaluate the performance of the  method with highest cross validation accuracy on test data.What is the accuracy value?

In [9]:
!pip install optuna

Collecting optuna
  Downloading optuna-2.10.0-py3-none-any.whl (308 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 308 kB 5.3 MB/s
Collecting alembic
  Downloading alembic-1.7.7-py3-none-any.whl (210 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 210 kB 34.3 MB/s
Collecting cliff
  Downloading cliff-3.10.1-py3-none-any.whl (81 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 81 kB 10.1 MB/s
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from optuna) (4.63.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from optuna) (1.21.5)
Requirement already satisfied: sqlalchemy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from optuna) (1.4.32)
Collecting cmaes>=0.8.2
  Downloading cmaes-0.8.2-py3-none-any.whl (15 kB)
Collecting colorlog
  Downloading colorlog-6.6.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: scipy!=1.4.0 in /usr/local/lib/python3.7/dist-packages (from optuna) (1.4.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.7/dist-packages (from optuna) (3.13)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from optuna) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->optuna) (3.0.7)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from sqlalchemy>=1.1.0->optuna) (1.1.2)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from sqlalchemy>=1.1.0->optuna) (4.11.3)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.7/dist-packages (from alembic->optuna) (5.4.0)
Collecting Mako
  Downloading Mako-1.2.0-py3-none-any.whl (78 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 78 kB 6.9 MB/s
Collecting cmd2>=1.0.0
  Downloading cmd2-2.4.0-py3-none-any.whl (150 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 150 kB 48.1 MB/s
Requirement already satisfied: PrettyTable>=0.7.2 in /usr/local/lib/python3.7/dist-packages (from cliff->optuna) (3.2.0)
Collecting stevedore>=2.0.1
  Downloading stevedore-3.5.0-py3-none-any.whl (49 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 49 kB 6.0 MB/s
Collecting autopage>=0.4.0
  Downloading autopage-0.5.0-py3-none-any.whl (29 kB)
Collecting pbr!=2.1.0,>=2.0.0
  Downloading pbr-5.8.1-py2.py3-none-any.whl (113 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 113 kB 46.0 MB/s
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from cmd2>=1.0.0->cliff->optuna) (3.10.0.2)
Requirement already satisfied: wcwidth>=0.1.7 in /usr/local/lib/python3.7/dist-packages (from cmd2>=1.0.0->cliff->optuna) (0.2.5)
Requirement already satisfied: attrs>=16.3.0 in /usr/local/lib/python3.7/dist-packages (from cmd2>=1.0.0->cliff->optuna) (21.4.0)
Collecting pyperclip>=1.6
  Downloading pyperclip-1.8.2.tar.gz (20 kB)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy>=1.1.0->optuna) (3.7.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.7/dist-packages (from Mako->alembic->optuna) (2.0.1)
Building wheels for collected packages: pyperclip
  Building wheel for pyperclip (setup.py) ... done
  Created wheel for pyperclip: filename=pyperclip-1.8.2-py3-none-any.whl size=11137 sha256=bb73ba19014207b3019107d51102997153dd30cec487adef0d41827b21236a28
  Stored in directory: /root/.cache/pip/wheels/9f/18/84/8f69f8b08169c7bae2dde6bd7daf0c19fca8c8e500ee620a28
Successfully built pyperclip
Installing collected packages: pyperclip, pbr, stevedore, Mako, cmd2, autopage, colorlog, cmaes, cliff, alembic, optuna
Successfully installed Mako-1.2.0 alembic-1.7.7 autopage-0.5.0 cliff-3.10.1 cmaes-0.8.2 cmd2-2.4.0 colorlog-6.6.0 optuna-2.10.0 pbr-5.8.1 pyperclip-1.8.2 stevedore-3.5.0

In [10]:
import optuna

import sklearn.datasets
import sklearn.ensemble
import sklearn.model_selection
import sklearn.svm

def objective(trial):
    x, y = X_test,y_test

    classifier_name = trial.suggest_categorical("classifier", ["Random Forest","XGBoost", "LightGBM","GradientBoostingClassifier" ])
    if classifier_name == "Random Forest":
         from sklearn.ensemble import RandomForestClassifier
         max_depth = trial.suggest_int("max_depth",2,X_test.shape[1])
         max_features = trial.suggest_int("max_features",2,X_test.shape[1])
         classifier_obj = sklearn.ensemble.RandomForestClassifier(random_state=15,  max_depth=max_depth, max_features=max_features )
        
         

    elif classifier_name == "XGBoost":
         from xgboost import XGBClassifier
         max_depth = trial.suggest_int("max_depth",2,X_test.shape[1])
         max_features = trial.suggest_int("max_features",2,X_test.shape[1])
         classifier_obj = XGBClassifier(random_state=15,  max_depth=max_depth, max_features=max_features )
        
         

    elif classifier_name == "LightGBM":
         import lightgbm as lgb
         max_depth = trial.suggest_int("max_depth",2,X_test.shape[1])
         max_features = trial.suggest_int("max_features",2,X_test.shape[1])
         classifier_obj = lgb.LGBMClassifier(random_state=15,  max_depth=max_depth, max_features=max_features )
         
    else:
         max_depth = trial.suggest_int("max_depth",2,X_test.shape[1])
         max_features = trial.suggest_int("max_features",2,X_test.shape[1])
         classifier_obj = sklearn.ensemble.GradientBoostingClassifier(random_state=15,  max_depth=max_depth, max_features=max_features )
        
         
    accuracy=sklearn.model_selection.cross_val_score(classifier_obj, x, y, n_jobs=-1, cv=3).mean()
   
    return accuracy

if __name__ == "__main__":
    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=100)
    print(study.best_trial)

[I 2022-03-27 18:57:07,741] A new study created in memory with name: no-name-b6fdd2eb-99aa-4251-854e-caaf269a9250
[I 2022-03-27 18:57:11,992] Trial 0 finished with value: 0.9030347867680198 and parameters: {'classifier': 'XGBoost', 'max_depth': 4, 'max_features': 7}. Best is trial 0 with value: 0.9030347867680198.
[I 2022-03-27 18:57:17,841] Trial 1 finished with value: 0.8982571765721277 and parameters: {'classifier': 'Random Forest', 'max_depth': 15, 'max_features': 14}. Best is trial 0 with value: 0.9030347867680198.
[I 2022-03-27 18:57:23,194] Trial 2 finished with value: 0.8994957466702963 and parameters: {'classifier': 'XGBoost', 'max_depth': 12, 'max_features': 7}. Best is trial 0 with value: 0.9030347867680198.
[I 2022-03-27 18:57:24,165] Trial 3 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 16}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:57:24,918] Trial 4 finished with value: 0.9020615624831502 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 13}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:57:26,791] Trial 5 finished with value: 0.9010887139424183 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 3, 'max_features': 9}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:57:27,564] Trial 6 finished with value: 0.9030348102520286 and parameters: {'classifier': 'LightGBM', 'max_depth': 14, 'max_features': 14}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:57:28,176] Trial 7 finished with value: 0.902061820807245 and parameters: {'classifier': 'LightGBM', 'max_depth': 6, 'max_features': 3}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:57:31,887] Trial 8 finished with value: 0.9017962871218769 and parameters: {'classifier': 'Random Forest', 'max_depth': 8, 'max_features': 10}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:57:40,035] Trial 9 finished with value: 0.9016194055690167 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 10, 'max_features': 6}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:57:40,785] Trial 10 finished with value: 0.9009117149695149 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 16}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:57:41,549] Trial 11 finished with value: 0.9013538718836486 and parameters: {'classifier': 'LightGBM', 'max_depth': 16, 'max_features': 16}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:57:42,297] Trial 12 finished with value: 0.9009117149695149 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 13}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:57:43,047] Trial 13 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 11}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:57:43,805] Trial 14 finished with value: 0.9022387728121312 and parameters: {'classifier': 'LightGBM', 'max_depth': 8, 'max_features': 15}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:57:44,564] Trial 15 finished with value: 0.9030348102520286 and parameters: {'classifier': 'LightGBM', 'max_depth': 14, 'max_features': 12}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:03,231] Trial 16 finished with value: 0.8976376449409528 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 11, 'max_features': 14}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:09,647] Trial 17 finished with value: 0.8992302599529456 and parameters: {'classifier': 'XGBoost', 'max_depth': 16, 'max_features': 12}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:10,886] Trial 18 finished with value: 0.8849861989178193 and parameters: {'classifier': 'Random Forest', 'max_depth': 6, 'max_features': 2}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:11,646] Trial 19 finished with value: 0.9030348102520286 and parameters: {'classifier': 'LightGBM', 'max_depth': 14, 'max_features': 10}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:12,399] Trial 20 finished with value: 0.9025041186254302 and parameters: {'classifier': 'LightGBM', 'max_depth': 9, 'max_features': 5}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:13,147] Trial 21 finished with value: 0.9030348102520286 and parameters: {'classifier': 'LightGBM', 'max_depth': 14, 'max_features': 10}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:13,900] Trial 22 finished with value: 0.9030348102520286 and parameters: {'classifier': 'LightGBM', 'max_depth': 14, 'max_features': 9}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:14,661] Trial 23 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 8}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:15,426] Trial 24 finished with value: 0.9029463225075811 and parameters: {'classifier': 'LightGBM', 'max_depth': 15, 'max_features': 10}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:16,173] Trial 25 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 4}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:18,257] Trial 26 finished with value: 0.9005576230876736 and parameters: {'classifier': 'Random Forest', 'max_depth': 10, 'max_features': 4}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:27,881] Trial 27 finished with value: 0.8976376449409528 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 11, 'max_features': 2}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:31,410] Trial 28 finished with value: 0.900822898448947 and parameters: {'classifier': 'XGBoost', 'max_depth': 8, 'max_features': 15}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:33,965] Trial 29 finished with value: 0.9022384205520021 and parameters: {'classifier': 'XGBoost', 'max_depth': 6, 'max_features': 6}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:34,723] Trial 30 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 8}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:35,477] Trial 31 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 8}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:36,236] Trial 32 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 7}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:36,888] Trial 33 finished with value: 0.9025041186254302 and parameters: {'classifier': 'LightGBM', 'max_depth': 9, 'max_features': 5}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:37,549] Trial 34 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 8}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:40,383] Trial 35 finished with value: 0.9017961227338166 and parameters: {'classifier': 'Random Forest', 'max_depth': 10, 'max_features': 7}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:41,146] Trial 36 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 4}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:41,903] Trial 37 finished with value: 0.9009117149695149 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 6}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:47,210] Trial 38 finished with value: 0.9018849392543847 and parameters: {'classifier': 'XGBoost', 'max_depth': 7, 'max_features': 8}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:59,423] Trial 39 finished with value: 0.898434105093005 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 10, 'max_features': 7}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:58:59,898] Trial 40 finished with value: 0.9025927237899207 and parameters: {'classifier': 'LightGBM', 'max_depth': 3, 'max_features': 3}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:00,564] Trial 41 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 8}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:01,332] Trial 42 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 9}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:02,078] Trial 43 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 7}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:02,840] Trial 44 finished with value: 0.9025041186254302 and parameters: {'classifier': 'LightGBM', 'max_depth': 9, 'max_features': 7}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:03,150] Trial 45 finished with value: 0.8988765907832593 and parameters: {'classifier': 'LightGBM', 'max_depth': 2, 'max_features': 5}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:03,920] Trial 46 finished with value: 0.9009117149695149 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 6}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:07,125] Trial 47 finished with value: 0.9014423126600787 and parameters: {'classifier': 'Random Forest', 'max_depth': 10, 'max_features': 8}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:07,886] Trial 48 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 9}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:15,899] Trial 49 finished with value: 0.9016194055690167 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 10, 'max_features': 6}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:16,654] Trial 50 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 11}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:17,412] Trial 51 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 4}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:18,178] Trial 52 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 4}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:18,948] Trial 53 finished with value: 0.9009117149695149 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 3}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:19,699] Trial 54 finished with value: 0.9025041186254302 and parameters: {'classifier': 'LightGBM', 'max_depth': 9, 'max_features': 13}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:20,452] Trial 55 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 4}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:21,224] Trial 56 finished with value: 0.9020615624831502 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 12}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:21,991] Trial 57 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 8}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:27,272] Trial 58 finished with value: 0.8994957466702963 and parameters: {'classifier': 'XGBoost', 'max_depth': 12, 'max_features': 8}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:28,011] Trial 59 finished with value: 0.9022387728121312 and parameters: {'classifier': 'LightGBM', 'max_depth': 8, 'max_features': 5}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:29,748] Trial 60 finished with value: 0.8971953236387589 and parameters: {'classifier': 'Random Forest', 'max_depth': 13, 'max_features': 2}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:30,515] Trial 61 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 7}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:31,277] Trial 62 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 10}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:32,040] Trial 63 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 7}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:32,824] Trial 64 finished with value: 0.9020615624831502 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 11}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:33,599] Trial 65 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 7}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:34,368] Trial 66 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 3}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:39,469] Trial 67 finished with value: 0.8979036248224843 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 9, 'max_features': 3}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:40,225] Trial 68 finished with value: 0.9020615624831502 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 9}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:40,995] Trial 69 finished with value: 0.9009117149695149 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 4}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:41,761] Trial 70 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 11}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:42,887] Trial 71 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 9}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:44,034] Trial 72 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 9}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:45,150] Trial 73 finished with value: 0.9020615624831502 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 3}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:49,170] Trial 74 finished with value: 0.9002036251418669 and parameters: {'classifier': 'XGBoost', 'max_depth': 9, 'max_features': 8}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:49,938] Trial 75 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 5}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:50,603] Trial 76 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 7}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:51,364] Trial 77 finished with value: 0.9029463225075811 and parameters: {'classifier': 'LightGBM', 'max_depth': 15, 'max_features': 10}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:54,011] Trial 78 finished with value: 0.9013538249156313 and parameters: {'classifier': 'Random Forest', 'max_depth': 10, 'max_features': 6}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:54,784] Trial 79 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 9}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:55,542] Trial 80 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 6}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:56,217] Trial 81 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 6}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:56,860] Trial 82 finished with value: 0.901265337171184 and parameters: {'classifier': 'LightGBM', 'max_depth': 5, 'max_features': 6}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:57,623] Trial 83 finished with value: 0.9020615624831502 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 8}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 18:59:58,387] Trial 84 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 4}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 19:00:10,645] Trial 85 finished with value: 0.8979918307588285 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 11, 'max_features': 11}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 19:00:11,407] Trial 86 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 9}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 19:00:12,164] Trial 87 finished with value: 0.9009117149695149 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 5}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 19:00:12,927] Trial 88 finished with value: 0.9025041186254302 and parameters: {'classifier': 'LightGBM', 'max_depth': 9, 'max_features': 4}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 19:00:17,399] Trial 89 finished with value: 0.8997613742916988 and parameters: {'classifier': 'XGBoost', 'max_depth': 10, 'max_features': 4}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 19:00:18,143] Trial 90 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 2}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 19:00:18,906] Trial 91 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 7}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 19:00:19,667] Trial 92 finished with value: 0.9020615624831502 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 5}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 19:00:20,321] Trial 93 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 8}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 19:00:21,084] Trial 94 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 4}. Best is trial 3 with value: 0.9041851744138532.
[I 2022-03-27 19:00:21,892] Trial 95 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 7}. Best is trial 3 with value: 0.9041851744138532.

FrozenTrial(number=3, values=[0.9041851744138532], datetime_start=datetime.datetime(2022, 3, 27, 18, 57, 23, 196621), datetime_complete=datetime.datetime(2022, 3, 27, 18, 57, 24, 165224), params={'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 16}, distributions={'classifier': CategoricalDistribution(choices=('Random Forest', 'XGBoost', 'LightGBM', 'GradientBoostingClassifier')), 'max_depth': IntUniformDistribution(high=16, low=2, step=1), 'max_features': IntUniformDistribution(high=16, low=2, step=1)}, user_attrs={}, system_attrs={}, intermediate_values={}, trial_id=3, state=TrialState.COMPLETE, value=None)

In [11]:
study.best_params

{'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 16}

In [12]:
import lightgbm as lgb
lgb_model = lgb.LGBMClassifier(random_state=15,max_depth=11,max_features=9)
lgb_model.fit(X_test, y_test)

print(accuracy_score(y_test, lgb_model.predict(X_test)))

0.95788728656109

For Q3 and Q4 ,use the following data.

In [13]:
dr=pd.read_csv('https://raw.githubusercontent.com/ogut77/DataScience/main/data/diamond.csv')
dr

,Carat Weight,Cut,Color,Clarity,Polish,Symmetry,Report,Price
0,1.10,Ideal,H,SI1,VG,EX,GIA,5169
1,0.83,Ideal,H,VS1,ID,ID,AGSL,3470
2,0.85,Ideal,H,SI1,EX,EX,GIA,3183
3,0.91,Ideal,E,SI1,VG,VG,GIA,4370
4,0.83,Ideal,G,SI1,EX,EX,GIA,3171
...,...,...,...,...,...,...,...,...
5995,1.03,Ideal,D,SI1,EX,EX,GIA,6250
5996,1.00,Very Good,D,SI1,VG,VG,GIA,5328
5997,1.02,Ideal,D,SI1,EX,EX,GIA,6157
5998,1.27,Signature-Ideal,G,VS1,EX,EX,GIA,11206
5999,2.19,Ideal,E,VS1,EX,EX,GIA,30507

In [14]:
def Encoder(df):
          from sklearn import preprocessing
          columnsToEncode = list(df.select_dtypes(include=['category','object']))
          le = preprocessing.LabelEncoder()
          for feature in columnsToEncode:
              try:
                  df[feature] = le.fit_transform(df[feature])
              except:
                  print('Error encoding '+feature)
          return df

In [15]:
dr=Encoder(dr)
dr

      Carat Weight  Cut  Color  Clarity  Polish  Symmetry  Report  Price
0             1.10    2      4        2       3         0       1   5169
1             0.83    2      4        3       2         2       0   3470
2             0.85    2      4        2       0         0       1   3183
3             0.91    2      1        2       3         3       1   4370
4             0.83    2      3        2       0         0       1   3171
...            ...  ...    ...      ...     ...       ...     ...    ...
5995          1.03    2      0        2       0         0       1   6250
5996          1.00    4      0        2       3         3       1   5328
5997          1.02    2      0        2       0         0       1   6157
5998          1.27    3      3        3       0         0       1  11206
5999          2.19    2      1        3       0         0       1  30507

[6000 rows x 8 columns]

In [16]:
y = dr['Price'] #Output
X = dr.drop('Price',axis=1)
X

      Carat Weight  Cut  Color  Clarity  Polish  Symmetry  Report
0             1.10    2      4        2       3         0       1
1             0.83    2      4        3       2         2       0
2             0.85    2      4        2       0         0       1
3             0.91    2      1        2       3         3       1
4             0.83    2      3        2       0         0       1
...            ...  ...    ...      ...     ...       ...     ...
5995          1.03    2      0        2       0         0       1
5996          1.00    4      0        2       3         3       1
5997          1.02    2      0        2       0         0       1
5998          1.27    3      3        3       0         0       1
5999          2.19    2      1        3       0         0       1

[6000 rows x 7 columns]

In [17]:
from sklearn.model_selection import  train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=17)

Q3)Using Linear Regression,Decison Tree Random Forest,XGBoost, Light GBM and Gradient Boosting Classifier with default parameters (no parameter specifications except random_state) calculate R2 statistics on test data. Which method gives the best accuracy on test data

In [18]:
from pandas.core.common import random_state
def evalmetric(y,ypred):
 import numpy as np
 e = y - ypred 
 mse_f = np.mean(e**2)
 rmse_f = np.sqrt(mse_f)
 mae_f = np.mean(abs(e))
 mape_f = 100*np.mean(abs(e/y))
 r2_f = 1-(sum(e**2)/sum((y-np.mean(y))**2))
 print("MSE:", mse_f)
 print("RMSE:", rmse_f)
 print("MAE:",mae_f)
 print("MAPE:",mape_f)
 print("R-Squared:", r2_f)

#Linear Regression
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train, y_train)

print('Linear Regression')
pred=reg.predict(X_test)
evalmetric(y_test,pred)
print( )

#Decision Tree
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(random_state=15)
dtr.fit(X_train,y_train)

print('Decision Tree')
y_pred2 = dtr.predict(X_test)
evalmetric(y_test,y_pred2)
print( )

#Random Forest
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(random_state=15)
rfr.fit(X_train,y_train)

print('Random Forest')
y_pred2 = rfr.predict(X_test)
evalmetric(y_test,y_pred2)
print( )

#XGBoost
from xgboost import XGBRegressor
xgr = XGBRegressor(random_state=15)
xgr.fit(X_train, y_train)

print('TXGBoost')
y_pred2 = xgr.predict(X_test)
evalmetric(y_test,y_pred2)
print( )

#Light GBM
from time import time
import lightgbm as lgb
t0 = time()
lgr = lgb.LGBMRegressor(random_state=15)
lgr.fit(X_train, y_train)

print('Light GBM')
y_pred2 = lgr.predict(X_test)
evalmetric(y_test,y_pred2)
print( )

#Gradient Boosting
from sklearn.ensemble import GradientBoostingRegressor
from time import time

gbr = GradientBoostingRegressor(random_state=15)
gbr.fit(X_train, y_train)

print('Gradient Boosting')
y_pred2 = gbr.predict(X_test)
evalmetric(y_test,y_pred2)

Linear Regression
MSE: 18292450.049325157
RMSE: 4276.967389322153
MAE: 2701.997276609754
MAPE: 30.68442425409791
R-Squared: 0.8233845829696962

Decision Tree
MSE: 3706593.620659981
RMSE: 1925.2515733430737
MAE: 989.8429285714286
MAPE: 7.822563429503463
R-Squared: 0.9642124714672173

Random Forest
MSE: 2053745.8883534386
RMSE: 1433.089630258149
MAE: 766.9832157841038
MAPE: 6.139558134085696
R-Squared: 0.9801708800315027

[19:18:24] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
TXGBoost
MSE: 2822838.991584785
RMSE: 1680.1306471774108
MAE: 881.3905965169271
MAPE: 7.3386749783130245
R-Squared: 0.9727452099437854

Light GBM
MSE: 1940840.8294753155
RMSE: 1393.1406352107153
MAE: 701.0864858904304
MAPE: 5.433753614630323
R-Squared: 0.9812609895578275

Gradient Boosting
MSE: 2702865.535065863
RMSE: 1644.0393958375398
MAE: 878.4993508475269
MAPE: 7.3941445030960065
R-Squared: 0.9739035655494326

Q4) Using optuna hyperparmeter optimization technique (100 trial)  with Random Forest,XGBoost, Light GBM and Gradient Boosting Regressor

a)find best methods with  parameters  using Cross validation (CV=3) technique for the range of   parameters below. What are the best parameters for the method with highest cross validation R2?

"max_depth": range(2, 7), "max_features": range(2, 7)

 b)Evaluate the performance of the  method with highest cross validation R2 on test data. What is the R2 value?

In [19]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.7/dist-packages (2.10.0)
Requirement already satisfied: alembic in /usr/local/lib/python3.7/dist-packages (from optuna) (1.7.7)
Requirement already satisfied: cliff in /usr/local/lib/python3.7/dist-packages (from optuna) (3.10.1)
Requirement already satisfied: sqlalchemy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from optuna) (1.4.32)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from optuna) (21.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from optuna) (4.63.0)
Requirement already satisfied: scipy!=1.4.0 in /usr/local/lib/python3.7/dist-packages (from optuna) (1.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from optuna) (1.21.5)
Requirement already satisfied: cmaes>=0.8.2 in /usr/local/lib/python3.7/dist-packages (from optuna) (0.8.2)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.7/dist-packages (from optuna) (3.13)
Requirement already satisfied: colorlog in /usr/local/lib/python3.7/dist-packages (from optuna) (6.6.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->optuna) (3.0.7)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from sqlalchemy>=1.1.0->optuna) (4.11.3)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from sqlalchemy>=1.1.0->optuna) (1.1.2)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.7/dist-packages (from alembic->optuna) (5.4.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.7/dist-packages (from alembic->optuna) (1.2.0)
Requirement already satisfied: autopage>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from cliff->optuna) (0.5.0)
Requirement already satisfied: cmd2>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from cliff->optuna) (2.4.0)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from cliff->optuna) (5.8.1)
Requirement already satisfied: stevedore>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from cliff->optuna) (3.5.0)
Requirement already satisfied: PrettyTable>=0.7.2 in /usr/local/lib/python3.7/dist-packages (from cliff->optuna) (3.2.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from cmd2>=1.0.0->cliff->optuna) (3.10.0.2)
Requirement already satisfied: attrs>=16.3.0 in /usr/local/lib/python3.7/dist-packages (from cmd2>=1.0.0->cliff->optuna) (21.4.0)
Requirement already satisfied: wcwidth>=0.1.7 in /usr/local/lib/python3.7/dist-packages (from cmd2>=1.0.0->cliff->optuna) (0.2.5)
Requirement already satisfied: pyperclip>=1.6 in /usr/local/lib/python3.7/dist-packages (from cmd2>=1.0.0->cliff->optuna) (1.8.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy>=1.1.0->optuna) (3.7.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.7/dist-packages (from Mako->alembic->optuna) (2.0.1)

In [20]:
import optuna

import sklearn.datasets
import sklearn.ensemble
import sklearn.model_selection
import sklearn.svm

def objective(trial):
    x, y = X_train,y_train

    regressor_name = trial.suggest_categorical("regressor", ["GradientBoosting", "XGBoost","LightGBM","RandomForest"])
    if regressor_name == "GradientBoosting":
         max_depth = trial.suggest_int("max_depth", 2,7)
         max_features = trial.suggest_int("max_features", 2,7)
         regressor_obj = sklearn.ensemble.GradientBoostingRegressor(random_state=15,  max_depth=max_depth, max_features=max_features )
    
    elif regressor_name == "XGBoost":
         from xgboost import XGBRegressor
         max_depth = trial.suggest_int("max_depth", 2,7)
         max_features = trial.suggest_int("max_features", 2,7)
         regressor_obj = XGBRegressor(random_state=15,  max_depth=max_depth, max_features=max_features )
        
         

    elif regressor_name == "LightGBM":
         import lightgbm as lgb
         max_depth = trial.suggest_int("max_depth", 2,7)
         max_features = trial.suggest_int("max_features", 2,7)
         regressor_obj = lgb.LGBMRegressor(random_state=15,  max_depth=max_depth, max_features=max_features )
        
       
   
    else:
         max_depth = trial.suggest_int("max_depth", 2,7)
         max_features = trial.suggest_int("max_features", 2,7)
         regressor_obj = sklearn.ensemble.RandomForestRegressor(random_state=15,  max_depth=max_depth, max_features=max_features )

     

    r2=sklearn.model_selection.cross_val_score(regressor_obj, x, y, n_jobs=-1, cv=3).mean()
   
    return r2


if __name__ == "__main__":
    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=100)
    print(study.best_trial)

[I 2022-03-27 19:20:13,615] A new study created in memory with name: no-name-a86fcc83-904e-4fb9-8e21-a72ac1531a06
[I 2022-03-27 19:20:15,453] Trial 0 finished with value: 0.9756878022034616 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 3, 'max_features': 4}. Best is trial 0 with value: 0.9756878022034616.
[I 2022-03-27 19:20:16,193] Trial 1 finished with value: 0.9844984658243762 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 7, 'max_features': 5}. Best is trial 1 with value: 0.9844984658243762.
[I 2022-03-27 19:20:16,504] Trial 2 finished with value: 0.9548589700649653 and parameters: {'regressor': 'XGBoost', 'max_depth': 2, 'max_features': 6}. Best is trial 1 with value: 0.9844984658243762.
[I 2022-03-27 19:20:17,036] Trial 3 finished with value: 0.9842502916631269 and parameters: {'regressor': 'XGBoost', 'max_depth': 5, 'max_features': 5}. Best is trial 1 with value: 0.9844984658243762.
[I 2022-03-27 19:20:17,607] Trial 4 finished with value: 0.8285058059505935 and parameters: {'regressor': 'RandomForest', 'max_depth': 5, 'max_features': 2}. Best is trial 1 with value: 0.9844984658243762.
[I 2022-03-27 19:20:17,956] Trial 5 finished with value: 0.9782782238976115 and parameters: {'regressor': 'XGBoost', 'max_depth': 3, 'max_features': 2}. Best is trial 1 with value: 0.9844984658243762.
[I 2022-03-27 19:20:18,357] Trial 6 finished with value: 0.9783260831547227 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 3, 'max_features': 5}. Best is trial 1 with value: 0.9844984658243762.
[I 2022-03-27 19:20:18,962] Trial 7 finished with value: 0.9845567951821383 and parameters: {'regressor': 'XGBoost', 'max_depth': 6, 'max_features': 7}. Best is trial 7 with value: 0.9845567951821383.
[I 2022-03-27 19:20:19,316] Trial 8 finished with value: 0.9706874365810324 and parameters: {'regressor': 'LightGBM', 'max_depth': 3, 'max_features': 4}. Best is trial 7 with value: 0.9845567951821383.
[I 2022-03-27 19:20:19,660] Trial 9 finished with value: 0.9782782238976115 and parameters: {'regressor': 'XGBoost', 'max_depth': 3, 'max_features': 6}. Best is trial 7 with value: 0.9845567951821383.
[I 2022-03-27 19:20:19,862] Trial 10 finished with value: 0.9758296442252078 and parameters: {'regressor': 'LightGBM', 'max_depth': 7, 'max_features': 7}. Best is trial 7 with value: 0.9845567951821383.
[I 2022-03-27 19:20:20,798] Trial 11 finished with value: 0.9843004863532617 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 7, 'max_features': 7}. Best is trial 7 with value: 0.9845567951821383.
[I 2022-03-27 19:20:21,481] Trial 12 finished with value: 0.9399496992871897 and parameters: {'regressor': 'RandomForest', 'max_depth': 6, 'max_features': 3}. Best is trial 7 with value: 0.9845567951821383.
[I 2022-03-27 19:20:22,195] Trial 13 finished with value: 0.9842632699866831 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 6}. Best is trial 7 with value: 0.9845567951821383.
[I 2022-03-27 19:20:22,984] Trial 14 finished with value: 0.9843782262600483 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 7}. Best is trial 7 with value: 0.9845567951821383.
[I 2022-03-27 19:20:23,689] Trial 15 finished with value: 0.9840024346566438 and parameters: {'regressor': 'XGBoost', 'max_depth': 7, 'max_features': 5}. Best is trial 7 with value: 0.9845567951821383.
[I 2022-03-27 19:20:23,879] Trial 16 finished with value: 0.9758941121368242 and parameters: {'regressor': 'LightGBM', 'max_depth': 6, 'max_features': 3}. Best is trial 7 with value: 0.9845567951821383.
[I 2022-03-27 19:20:24,654] Trial 17 finished with value: 0.9446194900183317 and parameters: {'regressor': 'RandomForest', 'max_depth': 5, 'max_features': 6}. Best is trial 7 with value: 0.9845567951821383.
[I 2022-03-27 19:20:25,369] Trial 18 finished with value: 0.9840024346566438 and parameters: {'regressor': 'XGBoost', 'max_depth': 7, 'max_features': 4}. Best is trial 7 with value: 0.9845567951821383.
[I 2022-03-27 19:20:25,946] Trial 19 finished with value: 0.9854252425741864 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 19 with value: 0.9854252425741864.
[I 2022-03-27 19:20:26,379] Trial 20 finished with value: 0.9837177913038949 and parameters: {'regressor': 'XGBoost', 'max_depth': 4, 'max_features': 7}. Best is trial 19 with value: 0.9854252425741864.
[I 2022-03-27 19:20:26,907] Trial 21 finished with value: 0.9848066097721494 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 6}. Best is trial 19 with value: 0.9854252425741864.
[I 2022-03-27 19:20:27,491] Trial 22 finished with value: 0.9854252425741864 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 19 with value: 0.9854252425741864.
[I 2022-03-27 19:20:28,002] Trial 23 finished with value: 0.9848066097721494 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 6}. Best is trial 19 with value: 0.9854252425741864.
[I 2022-03-27 19:20:28,583] Trial 24 finished with value: 0.9854252425741864 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 19 with value: 0.9854252425741864.
[I 2022-03-27 19:20:29,157] Trial 25 finished with value: 0.9854252425741864 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 19 with value: 0.9854252425741864.
[I 2022-03-27 19:20:29,534] Trial 26 finished with value: 0.9567810009858858 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 2, 'max_features': 7}. Best is trial 19 with value: 0.9854252425741864.
[I 2022-03-27 19:20:30,102] Trial 27 finished with value: 0.9854252425741864 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 19 with value: 0.9854252425741864.
[I 2022-03-27 19:20:30,730] Trial 28 finished with value: 0.9852871555716267 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 19 with value: 0.9854252425741864.
[I 2022-03-27 19:20:31,298] Trial 29 finished with value: 0.9854252425741864 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 19 with value: 0.9854252425741864.
[I 2022-03-27 19:20:31,645] Trial 30 finished with value: 0.954650955412356 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 2, 'max_features': 6}. Best is trial 19 with value: 0.9854252425741864.
[I 2022-03-27 19:20:32,211] Trial 31 finished with value: 0.9854252425741864 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 19 with value: 0.9854252425741864.
[I 2022-03-27 19:20:32,804] Trial 32 finished with value: 0.9854252425741864 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 19 with value: 0.9854252425741864.
[I 2022-03-27 19:20:33,490] Trial 33 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:34,108] Trial 34 finished with value: 0.9852871555716267 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:34,673] Trial 35 finished with value: 0.984857971675666 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 5}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:35,485] Trial 36 finished with value: 0.938881839610775 and parameters: {'regressor': 'RandomForest', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:35,909] Trial 37 finished with value: 0.9777604137888515 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 3, 'max_features': 6}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:36,078] Trial 38 finished with value: 0.9765224083258769 and parameters: {'regressor': 'LightGBM', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:36,387] Trial 39 finished with value: 0.9729907172697613 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 3, 'max_features': 3}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:36,868] Trial 40 finished with value: 0.9848826518313535 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 5}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:37,445] Trial 41 finished with value: 0.9854252425741864 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:38,025] Trial 42 finished with value: 0.9854252425741864 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:38,500] Trial 43 finished with value: 0.9793776037779164 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 3, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:39,202] Trial 44 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:39,957] Trial 45 finished with value: 0.9446194900183317 and parameters: {'regressor': 'RandomForest', 'max_depth': 5, 'max_features': 6}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:40,124] Trial 46 finished with value: 0.9765224083258769 and parameters: {'regressor': 'LightGBM', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:40,475] Trial 47 finished with value: 0.9784438476442162 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 2}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:41,201] Trial 48 finished with value: 0.9842632699866831 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 6}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:41,686] Trial 49 finished with value: 0.9793776037779164 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 3, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:42,505] Trial 50 finished with value: 0.9640929729158358 and parameters: {'regressor': 'RandomForest', 'max_depth': 6, 'max_features': 6}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:43,095] Trial 51 finished with value: 0.9854252425741864 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:43,689] Trial 52 finished with value: 0.9854252425741864 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:44,378] Trial 53 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:45,070] Trial 54 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:45,589] Trial 55 finished with value: 0.9842502916631269 and parameters: {'regressor': 'XGBoost', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:45,787] Trial 56 finished with value: 0.9758941121368242 and parameters: {'regressor': 'LightGBM', 'max_depth': 6, 'max_features': 6}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:46,464] Trial 57 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:47,160] Trial 58 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:47,790] Trial 59 finished with value: 0.9852871555716267 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:48,474] Trial 60 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:49,159] Trial 61 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:49,955] Trial 62 finished with value: 0.9843782262600483 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:50,648] Trial 63 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:51,345] Trial 64 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:51,961] Trial 65 finished with value: 0.9845567951821383 and parameters: {'regressor': 'XGBoost', 'max_depth': 6, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:52,457] Trial 66 finished with value: 0.9841571098443246 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 4}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:53,153] Trial 67 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:53,777] Trial 68 finished with value: 0.9852871555716267 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:54,416] Trial 69 finished with value: 0.9219702558676274 and parameters: {'regressor': 'RandomForest', 'max_depth': 5, 'max_features': 3}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:55,219] Trial 70 finished with value: 0.9843782262600483 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:55,907] Trial 71 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:56,600] Trial 72 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:57,287] Trial 73 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:57,977] Trial 74 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:58,774] Trial 75 finished with value: 0.9843782262600483 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:58,946] Trial 76 finished with value: 0.9765224083258769 and parameters: {'regressor': 'LightGBM', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:20:59,653] Trial 77 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:21:00,286] Trial 78 finished with value: 0.9852871555716267 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:21:00,898] Trial 79 finished with value: 0.9845567951821383 and parameters: {'regressor': 'XGBoost', 'max_depth': 6, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:21:01,583] Trial 80 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:21:02,282] Trial 81 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:21:02,986] Trial 82 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:21:03,768] Trial 83 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:21:05,080] Trial 84 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:21:05,777] Trial 85 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:21:06,262] Trial 86 finished with value: 0.9841571098443246 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 4}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:21:06,961] Trial 87 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:21:07,596] Trial 88 finished with value: 0.9852871555716267 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:21:08,395] Trial 89 finished with value: 0.938881839610775 and parameters: {'regressor': 'RandomForest', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:21:09,043] Trial 90 finished with value: 0.9851775266807685 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 5}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:21:09,754] Trial 91 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:21:10,447] Trial 92 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.
[I 2022-03-27 19:21:11,138] Trial 93 finished with value: 0.9854840921446306 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 33 with value: 0.9854840921446306.

FrozenTrial(number=33, values=[0.9854840921446306], datetime_start=datetime.datetime(2022, 3, 27, 19, 20, 32, 806261), datetime_complete=datetime.datetime(2022, 3, 27, 19, 20, 33, 489889), params={'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}, distributions={'regressor': CategoricalDistribution(choices=('GradientBoosting', 'XGBoost', 'LightGBM', 'RandomForest')), 'max_depth': IntUniformDistribution(high=7, low=2, step=1), 'max_features': IntUniformDistribution(high=7, low=2, step=1)}, user_attrs={}, system_attrs={}, intermediate_values={}, trial_id=33, state=TrialState.COMPLETE, value=None)

In [21]:
print(study.best_params)

{'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}

In [22]:
from sklearn.ensemble import GradientBoostingRegressor
from time import time
gbr = GradientBoostingRegressor(random_state=15,max_depth= 6,max_features= 5)
gbr.fit(X_train, y_train)

print('Test Data')
y_pred2 = gbr.predict(X_test)
evalmetric(y_test,y_pred2)

Test Data
MSE: 1596195.4039618105
RMSE: 1263.4062703508364
MAE: 675.3187167627658
MAPE: 5.303612875028567
R-Squared: 0.9845885752771008